name = "Skyepack"
author = "skyenet"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4912622f837b372bdfed59bc70315a5fa195666a6cc3d3a8189c417f8ad91292"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
