name = "Skyepack"
author = "skyenet"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "312d5c391638ec80756fadc3b3d852962d636a4a39e96b03793728aa037bb15b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
