name = "Skyepack"
author = "skyenet"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b299a3a283422a0e026eba470da4f30708df5183e0fa86d9784960acfcc1ad"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
