name = "Architectury API (UNUSED)"
filename = "architectury-3.9.55.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "323a69a6268c44d383ec0a4db401f41034b4ed4f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3782809
project-id = 419697
