name = "Architectury API (Fabric)"
filename = "architectury-3.2.57.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3576/373/architectury-3.2.57.jar"
hash-format = "murmur2"
hash = "1668042498"

[update]
[update.curseforge]
file-id = 3576373
project-id = 419697
