name = "Custom Entity Models (CEM)"
filename = "cem-0.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/474/cem-0.7.0.jar"
hash-format = "murmur2"
hash = "3362249222"

[update]
[update.curseforge]
file-id = 3561474
project-id = 477078
