name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/643/InventoryProfilesNext-fabric-1.18-1.2.3.jar"
hash-format = "murmur2"
hash = "789874573"

[update]
[update.curseforge]
file-id = 3587643
project-id = 495267
