name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.19-1.8.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "f2544cc9e8dcaa0cdd97d366af4583419ff0e03e"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4010019
project-id = 495267
