name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/506/InventoryProfilesNext-fabric-1.18-1.3.4.jar"
hash-format = "sha1"
hash = "4b16157bba7a1838940ab5d25ebef1cdfc127994"

[update]
[update.curseforge]
file-id = 3658506
project-id = 495267
