name = "Mouse Tweaks"
filename = "MouseTweaks-fabric-mc1.18-2.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/798/MouseTweaks-fabric-mc1.18-2.20.jar"
hash-format = "murmur2"
hash = "954936443"

[update]
[update.curseforge]
file-id = 3577798
project-id = 60089
