name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.18.1-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/724/reeses_sodium_options-mc1.18.1-1.3.0.jar"
hash-format = "murmur2"
hash = "2910872584"

[update]
[update.curseforge]
file-id = 3596724
project-id = 511319
