name = "WTHIT"
filename = "wthit-fabric-5.13.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "e6337c5dd0daf19f2884255ea2a52a68d8bce931"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4025662
project-id = 440979
