name = "Xaero's World Map"
filename = "XaerosWorldMap_1.19.1_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/516/XaerosWorldMap_1.19.1_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "1812351466"

[update]
[update.curseforge]
file-id = 3599516
project-id = 317780
