name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.23.1_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/501/Xaeros_Minimap_21.23.1_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "3351685190"

[update]
[update.curseforge]
file-id = 3599501
project-id = 263420
