name = "Xaero's World Map"
filename = "XaerosWorldMap_1.18.8_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3574/78/XaerosWorldMap_1.18.8_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "4091458765"

[update]
[update.curseforge]
file-id = 3574078
project-id = 317780
