name = "Xaero's World Map"
filename = "XaerosWorldMap_1.19.0_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3582/991/XaerosWorldMap_1.19.0_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "1471680757"

[update]
[update.curseforge]
file-id = 3582991
project-id = 317780
